// Copyright 2023 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// This file includes the Safe Browsing V5 API SearchHashes and
// BatchGetHashLists request and response protocol buffers, since that's the
// only portion of the V5 API that Chrome currently uses. They should be kept in
// sync with the server implementation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: safebrowsingv5.proto

package safebrowsing_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Types of threats.
type ThreatType int32

const (
	// Unknown.
	ThreatType_THREAT_TYPE_UNSPECIFIED ThreatType = 0
	// Malware threat type.
	ThreatType_MALWARE ThreatType = 1
	// Social engineering threat type.
	ThreatType_SOCIAL_ENGINEERING ThreatType = 2
	// Unwanted software threat type.
	ThreatType_UNWANTED_SOFTWARE ThreatType = 3
	// Potentially harmful application threat type.
	ThreatType_POTENTIALLY_HARMFUL_APPLICATION ThreatType = 4
	// Malicious binary threat type.
	ThreatType_MALICIOUS_BINARY ThreatType = 7
	// Patterns to be used for activating the subresource filter.
	ThreatType_SUBRESOURCE_FILTER ThreatType = 13
	// Trick-to-bill threat list.
	ThreatType_TRICK_TO_BILL ThreatType = 15
	// Abusive experience violation threat type.
	ThreatType_ABUSIVE_EXPERIENCE_VIOLATION ThreatType = 20
	// Better advertisements threat type.
	ThreatType_BETTER_ADS_VIOLATION ThreatType = 21
	ThreatType_NOTIFICATION_ABUSE   ThreatType = 24
)

// Enum value maps for ThreatType.
var (
	ThreatType_name = map[int32]string{
		0:  "THREAT_TYPE_UNSPECIFIED",
		1:  "MALWARE",
		2:  "SOCIAL_ENGINEERING",
		3:  "UNWANTED_SOFTWARE",
		4:  "POTENTIALLY_HARMFUL_APPLICATION",
		7:  "MALICIOUS_BINARY",
		13: "SUBRESOURCE_FILTER",
		15: "TRICK_TO_BILL",
		20: "ABUSIVE_EXPERIENCE_VIOLATION",
		21: "BETTER_ADS_VIOLATION",
		24: "NOTIFICATION_ABUSE",
	}
	ThreatType_value = map[string]int32{
		"THREAT_TYPE_UNSPECIFIED":         0,
		"MALWARE":                         1,
		"SOCIAL_ENGINEERING":              2,
		"UNWANTED_SOFTWARE":               3,
		"POTENTIALLY_HARMFUL_APPLICATION": 4,
		"MALICIOUS_BINARY":                7,
		"SUBRESOURCE_FILTER":              13,
		"TRICK_TO_BILL":                   15,
		"ABUSIVE_EXPERIENCE_VIOLATION":    20,
		"BETTER_ADS_VIOLATION":            21,
		"NOTIFICATION_ABUSE":              24,
	}
)

func (x ThreatType) Enum() *ThreatType {
	p := new(ThreatType)
	*p = x
	return p
}

func (x ThreatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThreatType) Descriptor() protoreflect.EnumDescriptor {
	return file_safebrowsingv5_proto_enumTypes[0].Descriptor()
}

func (ThreatType) Type() protoreflect.EnumType {
	return &file_safebrowsingv5_proto_enumTypes[0]
}

func (x ThreatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThreatType.Descriptor instead.
func (ThreatType) EnumDescriptor() ([]byte, []int) {
	return file_safebrowsingv5_proto_rawDescGZIP(), []int{0}
}

// Attributes of threats. These attributes may confer additional meaning to a
// particular threat but will not affect the threat type. For example, an
// attribute may specify a lower confidence while a different attribute may
// specify higher confidence. More attributes may be added in the future.
type ThreatAttribute int32

const (
	// Unknown.
	ThreatAttribute_THREAT_ATTRIBUTE_UNSPECIFIED ThreatAttribute = 0
	// Indicates that the threat_type should not be used for enforcement.
	ThreatAttribute_CANARY ThreatAttribute = 1
	// Indicates that the threat_type should only be used for enforcement on
	// frames.
	ThreatAttribute_FRAME_ONLY ThreatAttribute = 2
)

// Enum value maps for ThreatAttribute.
var (
	ThreatAttribute_name = map[int32]string{
		0: "THREAT_ATTRIBUTE_UNSPECIFIED",
		1: "CANARY",
		2: "FRAME_ONLY",
	}
	ThreatAttribute_value = map[string]int32{
		"THREAT_ATTRIBUTE_UNSPECIFIED": 0,
		"CANARY":                       1,
		"FRAME_ONLY":                   2,
	}
)

func (x ThreatAttribute) Enum() *ThreatAttribute {
	p := new(ThreatAttribute)
	*p = x
	return p
}

func (x ThreatAttribute) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThreatAttribute) Descriptor() protoreflect.EnumDescriptor {
	return file_safebrowsingv5_proto_enumTypes[1].Descriptor()
}

func (ThreatAttribute) Type() protoreflect.EnumType {
	return &file_safebrowsingv5_proto_enumTypes[1]
}

func (x ThreatAttribute) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThreatAttribute.Descriptor instead.
func (ThreatAttribute) EnumDescriptor() ([]byte, []int) {
	return file_safebrowsingv5_proto_rawDescGZIP(), []int{1}
}

// Types of likely-safe sites.
//
// Note that the `SearchHashesResponse` intentionally does not contain
// `LikelySafeType`.
type LikelySafeType int32

const (
	// Unknown.
	LikelySafeType_LIKELY_SAFE_TYPE_UNSPECIFIED LikelySafeType = 0
	// This site is likely safe enough for general browsing. This is also known as
	// the global cache.
	LikelySafeType_GENERAL_BROWSING LikelySafeType = 1
	// This site is likely safe enough that there is no need to run Client-Side
	// Detection models or password protection checks.
	LikelySafeType_CSD LikelySafeType = 2
	// This site is likely safe enough that downloads from the site need not be
	// checked.
	LikelySafeType_DOWNLOAD LikelySafeType = 3
)

// Enum value maps for LikelySafeType.
var (
	LikelySafeType_name = map[int32]string{
		0: "LIKELY_SAFE_TYPE_UNSPECIFIED",
		1: "GENERAL_BROWSING",
		2: "CSD",
		3: "DOWNLOAD",
	}
	LikelySafeType_value = map[string]int32{
		"LIKELY_SAFE_TYPE_UNSPECIFIED": 0,
		"GENERAL_BROWSING":             1,
		"CSD":                          2,
		"DOWNLOAD":                     3,
	}
)

func (x LikelySafeType) Enum() *LikelySafeType {
	p := new(LikelySafeType)
	*p = x
	return p
}

func (x LikelySafeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LikelySafeType) Descriptor() protoreflect.EnumDescriptor {
	return file_safebrowsingv5_proto_enumTypes[2].Descriptor()
}

func (LikelySafeType) Type() protoreflect.EnumType {
	return &file_safebrowsingv5_proto_enumTypes[2]
}

func (x LikelySafeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LikelySafeType.Descriptor instead.
func (LikelySafeType) EnumDescriptor() ([]byte, []int) {
	return file_safebrowsingv5_proto_rawDescGZIP(), []int{2}
}

// The length of hashes in a hash list.
type HashListMetadata_HashLength int32

const (
	// Unspecified length.
	HashListMetadata_HASH_LENGTH_UNSPECIFIED HashListMetadata_HashLength = 0
	// Each hash is a four-byte prefix.
	HashListMetadata_FOUR_BYTES HashListMetadata_HashLength = 2
	// Each hash is an eight-byte prefix.
	HashListMetadata_EIGHT_BYTES HashListMetadata_HashLength = 3
	// Each hash is a sixteen-byte prefix.
	HashListMetadata_SIXTEEN_BYTES HashListMetadata_HashLength = 4
	// Each hash is a thirty-two-byte full hash.
	HashListMetadata_THIRTY_TWO_BYTES HashListMetadata_HashLength = 5
)

// Enum value maps for HashListMetadata_HashLength.
var (
	HashListMetadata_HashLength_name = map[int32]string{
		0: "HASH_LENGTH_UNSPECIFIED",
		2: "FOUR_BYTES",
		3: "EIGHT_BYTES",
		4: "SIXTEEN_BYTES",
		5: "THIRTY_TWO_BYTES",
	}
	HashListMetadata_HashLength_value = map[string]int32{
		"HASH_LENGTH_UNSPECIFIED": 0,
		"FOUR_BYTES":              2,
		"EIGHT_BYTES":             3,
		"SIXTEEN_BYTES":           4,
		"THIRTY_TWO_BYTES":        5,
	}
)

func (x HashListMetadata_HashLength) Enum() *HashListMetadata_HashLength {
	p := new(HashListMetadata_HashLength)
	*p = x
	return p
}

func (x HashListMetadata_HashLength) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HashListMetadata_HashLength) Descriptor() protoreflect.EnumDescriptor {
	return file_safebrowsingv5_proto_enumTypes[3].Descriptor()
}

func (HashListMetadata_HashLength) Type() protoreflect.EnumType {
	return &file_safebrowsingv5_proto_enumTypes[3]
}

func (x HashListMetadata_HashLength) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HashListMetadata_HashLength.Descriptor instead.
func (HashListMetadata_HashLength) EnumDescriptor() ([]byte, []int) {
	return file_safebrowsingv5_proto_rawDescGZIP(), []int{9, 0}
}

// A request that the client issues to search for specific hash prefixes. Note
// that currently this only searches threat lists, and does not search the
// global cache.
type SearchHashesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The hash prefixes to be looked up.
	HashPrefixes  [][]byte `protobuf:"bytes,1,rep,name=hash_prefixes,json=hashPrefixes,proto3" json:"hash_prefixes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHashesRequest) Reset() {
	*x = SearchHashesRequest{}
	mi := &file_safebrowsingv5_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHashesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHashesRequest) ProtoMessage() {}

func (x *SearchHashesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_safebrowsingv5_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHashesRequest.ProtoReflect.Descriptor instead.
func (*SearchHashesRequest) Descriptor() ([]byte, []int) {
	return file_safebrowsingv5_proto_rawDescGZIP(), []int{0}
}

func (x *SearchHashesRequest) GetHashPrefixes() [][]byte {
	if x != nil {
		return x.HashPrefixes
	}
	return nil
}

// The response returned after searching threat hashes. Note that if nothing is
// found, the server will return an OK status (HTTP status code 200) with
// the `full_hashes` field empty, rather than returning a NOT_FOUND status
// (HTTP status code 404).
type SearchHashesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unordered list of full hashes found.
	FullHashes []*FullHash `protobuf:"bytes,1,rep,name=full_hashes,json=fullHashes,proto3" json:"full_hashes,omitempty"`
	// The client-side cache duration. The client shall add this duration to the
	// current time to determine the expiration time. The expiration time then
	// applies to every hash prefix queried by the client in the request,
	// regardless of how many full hashes are returned in the response. Even if
	// the server returns no full hashes for a particular hash prefix, this fact
	// should also be cached by the client.
	//
	// Important: the client must not assume that the server will return the same
	// cache duration for all responses. The server may choose different cache
	// durations for different responses depending on the situation.
	CacheDuration *Duration `protobuf:"bytes,2,opt,name=cache_duration,json=cacheDuration,proto3" json:"cache_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHashesResponse) Reset() {
	*x = SearchHashesResponse{}
	mi := &file_safebrowsingv5_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHashesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHashesResponse) ProtoMessage() {}

func (x *SearchHashesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_safebrowsingv5_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHashesResponse.ProtoReflect.Descriptor instead.
func (*SearchHashesResponse) Descriptor() ([]byte, []int) {
	return file_safebrowsingv5_proto_rawDescGZIP(), []int{1}
}

func (x *SearchHashesResponse) GetFullHashes() []*FullHash {
	if x != nil {
		return x.FullHashes
	}
	return nil
}

func (x *SearchHashesResponse) GetCacheDuration() *Duration {
	if x != nil {
		return x.CacheDuration
	}
	return nil
}

// The full hash identified with one or more matches.
type FullHash struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The matching full hash. This is the SHA256 hash. The length will be exactly
	// 32 bytes.
	FullHash []byte `protobuf:"bytes,1,opt,name=full_hash,json=fullHash,proto3" json:"full_hash,omitempty"`
	// A repeated field identifying the details relevant to this full hash.
	FullHashDetails []*FullHash_FullHashDetail `protobuf:"bytes,2,rep,name=full_hash_details,json=fullHashDetails,proto3" json:"full_hash_details,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FullHash) Reset() {
	*x = FullHash{}
	mi := &file_safebrowsingv5_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullHash) ProtoMessage() {}

func (x *FullHash) ProtoReflect() protoreflect.Message {
	mi := &file_safebrowsingv5_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullHash.ProtoReflect.Descriptor instead.
func (*FullHash) Descriptor() ([]byte, []int) {
	return file_safebrowsingv5_proto_rawDescGZIP(), []int{2}
}

func (x *FullHash) GetFullHash() []byte {
	if x != nil {
		return x.FullHash
	}
	return nil
}

func (x *FullHash) GetFullHashDetails() []*FullHash_FullHashDetail {
	if x != nil {
		return x.FullHashDetails
	}
	return nil
}

type Duration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signed seconds of the span of time. Must be from -315,576,000,000
	// to +315,576,000,000 inclusive. Note: these bounds are computed from:
	// 60 sec/min * 60 min/hr * 24 hr/day * 365.25 days/year * 10000 years
	Seconds int64 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	// Signed fractions of a second at nanosecond resolution of the span
	// of time. Durations less than one second are represented with a 0
	// `seconds` field and a positive or negative `nanos` field. For durations
	// of one second or more, a non-zero value for the `nanos` field must be
	// of the same sign as the `seconds` field. Must be from -999,999,999
	// to +999,999,999 inclusive.
	Nanos         int32 `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Duration) Reset() {
	*x = Duration{}
	mi := &file_safebrowsingv5_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duration) ProtoMessage() {}

func (x *Duration) ProtoReflect() protoreflect.Message {
	mi := &file_safebrowsingv5_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duration.ProtoReflect.Descriptor instead.
func (*Duration) Descriptor() ([]byte, []int) {
	return file_safebrowsingv5_proto_rawDescGZIP(), []int{3}
}

func (x *Duration) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Duration) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

// The constraints on the sizes of the hash lists.
type SizeConstraints struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum size in number of entries. The update will not contain more
	// entries than this value, but it is possible that the update will contain
	// fewer entries than this value. This MUST be at least 1024. If omitted or
	// zero, no update size limit is set.
	MaxUpdateEntries int32 `protobuf:"varint,1,opt,name=max_update_entries,json=maxUpdateEntries,proto3" json:"max_update_entries,omitempty"`
	// Sets the maximum number of entries that the client is willing to have
	// in the local database for the list. (The server MAY cause the client to
	// store less than this number of entries.) If omitted or zero, no database
	// size limit is set.
	MaxDatabaseEntries int32 `protobuf:"varint,2,opt,name=max_database_entries,json=maxDatabaseEntries,proto3" json:"max_database_entries,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SizeConstraints) Reset() {
	*x = SizeConstraints{}
	mi := &file_safebrowsingv5_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizeConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeConstraints) ProtoMessage() {}

func (x *SizeConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_safebrowsingv5_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeConstraints.ProtoReflect.Descriptor instead.
func (*SizeConstraints) Descriptor() ([]byte, []int) {
	return file_safebrowsingv5_proto_rawDescGZIP(), []int{4}
}

func (x *SizeConstraints) GetMaxUpdateEntries() int32 {
	if x != nil {
		return x.MaxUpdateEntries
	}
	return 0
}

func (x *SizeConstraints) GetMaxDatabaseEntries() int32 {
	if x != nil {
		return x.MaxDatabaseEntries
	}
	return 0
}

// The Rice-Golomb encoded data. Used for either hashes or
// removal indices. It is guaranteed that every hash or index here has the same
// length, and this length is exactly 32 bits.
//
// Generally speaking, if we sort all the entries lexicographically, we will
// find that the higher order bits tend not to change as frequently as lower
// order bits. This means that if we also take the adjacent difference between
// entries, the higher order bits have a high probability of being zero. This
// exploits this high probability of zero by essentially choosing a certain
// number of bits; all bits more significant than this are likely to be zero so
// we use unary encoding. See the `rice_parameter` field.
//
// Historical note: the Rice-delta encoding was first used in V4 of this API. In
// V5, two significant improvements were made: firstly, the Rice-delta encoding
// is now available with hash prefixes longer than 4 bytes; secondly, the
// encoded data are now treated as big-endian so as to avoid a costly sorting
// step.
type RiceDeltaEncoded32Bit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The first entry in the encoded data (hashes or indices), or, if only a
	// single hash prefix or index was encoded, that entry's value. If the field
	// is empty, the entry is zero.
	FirstValue uint32 `protobuf:"varint,1,opt,name=first_value,json=firstValue,proto3" json:"first_value,omitempty"`
	// The Golomb-Rice parameter. This parameter is guaranteed to be between 3 and
	// 30, inclusive.
	RiceParameter int32 `protobuf:"varint,2,opt,name=rice_parameter,json=riceParameter,proto3" json:"rice_parameter,omitempty"`
	// The number of entries that are delta encoded in the encoded data. If only a
	// single integer was encoded, this will be zero and the single value will be
	// stored in `first_value`.
	EntriesCount int32 `protobuf:"varint,3,opt,name=entries_count,json=entriesCount,proto3" json:"entries_count,omitempty"`
	// The encoded deltas that are encoded using the Golomb-Rice coder.
	EncodedData   []byte `protobuf:"bytes,4,opt,name=encoded_data,json=encodedData,proto3" json:"encoded_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiceDeltaEncoded32Bit) Reset() {
	*x = RiceDeltaEncoded32Bit{}
	mi := &file_safebrowsingv5_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiceDeltaEncoded32Bit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiceDeltaEncoded32Bit) ProtoMessage() {}

func (x *RiceDeltaEncoded32Bit) ProtoReflect() protoreflect.Message {
	mi := &file_safebrowsingv5_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiceDeltaEncoded32Bit.ProtoReflect.Descriptor instead.
func (*RiceDeltaEncoded32Bit) Descriptor() ([]byte, []int) {
	return file_safebrowsingv5_proto_rawDescGZIP(), []int{5}
}

func (x *RiceDeltaEncoded32Bit) GetFirstValue() uint32 {
	if x != nil {
		return x.FirstValue
	}
	return 0
}

func (x *RiceDeltaEncoded32Bit) GetRiceParameter() int32 {
	if x != nil {
		return x.RiceParameter
	}
	return 0
}

func (x *RiceDeltaEncoded32Bit) GetEntriesCount() int32 {
	if x != nil {
		return x.EntriesCount
	}
	return 0
}

func (x *RiceDeltaEncoded32Bit) GetEncodedData() []byte {
	if x != nil {
		return x.EncodedData
	}
	return nil
}

// Same as `RiceDeltaEncoded32Bit` except this encodes 64-bit numbers.
type RiceDeltaEncoded64Bit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The first entry in the encoded data (hashes), or, if only a single
	// hash prefix was encoded, that entry's value. If the field is empty, the
	// entry is zero.
	FirstValue uint64 `protobuf:"varint,1,opt,name=first_value,json=firstValue,proto3" json:"first_value,omitempty"`
	// The Golomb-Rice parameter. This parameter is guaranteed to be between 35
	// and 62, inclusive.
	RiceParameter int32 `protobuf:"varint,2,opt,name=rice_parameter,json=riceParameter,proto3" json:"rice_parameter,omitempty"`
	// The number of entries that are delta encoded in the encoded data. If only a
	// single integer was encoded, this will be zero and the single value will be
	// stored in `first_value`.
	EntriesCount int32 `protobuf:"varint,3,opt,name=entries_count,json=entriesCount,proto3" json:"entries_count,omitempty"`
	// The encoded deltas that are encoded using the Golomb-Rice coder.
	EncodedData   []byte `protobuf:"bytes,4,opt,name=encoded_data,json=encodedData,proto3" json:"encoded_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiceDeltaEncoded64Bit) Reset() {
	*x = RiceDeltaEncoded64Bit{}
	mi := &file_safebrowsingv5_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiceDeltaEncoded64Bit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiceDeltaEncoded64Bit) ProtoMessage() {}

func (x *RiceDeltaEncoded64Bit) ProtoReflect() protoreflect.Message {
	mi := &file_safebrowsingv5_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiceDeltaEncoded64Bit.ProtoReflect.Descriptor instead.
func (*RiceDeltaEncoded64Bit) Descriptor() ([]byte, []int) {
	return file_safebrowsingv5_proto_rawDescGZIP(), []int{6}
}

func (x *RiceDeltaEncoded64Bit) GetFirstValue() uint64 {
	if x != nil {
		return x.FirstValue
	}
	return 0
}

func (x *RiceDeltaEncoded64Bit) GetRiceParameter() int32 {
	if x != nil {
		return x.RiceParameter
	}
	return 0
}

func (x *RiceDeltaEncoded64Bit) GetEntriesCount() int32 {
	if x != nil {
		return x.EntriesCount
	}
	return 0
}

func (x *RiceDeltaEncoded64Bit) GetEncodedData() []byte {
	if x != nil {
		return x.EncodedData
	}
	return nil
}

// Same as `RiceDeltaEncoded32Bit` except this encodes 128-bit numbers.
type RiceDeltaEncoded128Bit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The upper 64 bits of the first entry in the encoded data (hashes). If the
	// field is empty, the upper 64 bits are all zero.
	FirstValueHi uint64 `protobuf:"varint,1,opt,name=first_value_hi,json=firstValueHi,proto3" json:"first_value_hi,omitempty"`
	// The lower 64 bits of the first entry in the encoded data (hashes). If the
	// field is empty, the lower 64 bits are all zero.
	FirstValueLo uint64 `protobuf:"fixed64,2,opt,name=first_value_lo,json=firstValueLo,proto3" json:"first_value_lo,omitempty"`
	// The Golomb-Rice parameter. This parameter is guaranteed to be between 99
	// and 126, inclusive.
	RiceParameter int32 `protobuf:"varint,3,opt,name=rice_parameter,json=riceParameter,proto3" json:"rice_parameter,omitempty"`
	// The number of entries that are delta encoded in the encoded data. If only a
	// single integer was encoded, this will be zero and the single value will be
	// stored in `first_value`.
	EntriesCount int32 `protobuf:"varint,4,opt,name=entries_count,json=entriesCount,proto3" json:"entries_count,omitempty"`
	// The encoded deltas that are encoded using the Golomb-Rice coder.
	EncodedData   []byte `protobuf:"bytes,5,opt,name=encoded_data,json=encodedData,proto3" json:"encoded_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiceDeltaEncoded128Bit) Reset() {
	*x = RiceDeltaEncoded128Bit{}
	mi := &file_safebrowsingv5_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiceDeltaEncoded128Bit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiceDeltaEncoded128Bit) ProtoMessage() {}

func (x *RiceDeltaEncoded128Bit) ProtoReflect() protoreflect.Message {
	mi := &file_safebrowsingv5_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiceDeltaEncoded128Bit.ProtoReflect.Descriptor instead.
func (*RiceDeltaEncoded128Bit) Descriptor() ([]byte, []int) {
	return file_safebrowsingv5_proto_rawDescGZIP(), []int{7}
}

func (x *RiceDeltaEncoded128Bit) GetFirstValueHi() uint64 {
	if x != nil {
		return x.FirstValueHi
	}
	return 0
}

func (x *RiceDeltaEncoded128Bit) GetFirstValueLo() uint64 {
	if x != nil {
		return x.FirstValueLo
	}
	return 0
}

func (x *RiceDeltaEncoded128Bit) GetRiceParameter() int32 {
	if x != nil {
		return x.RiceParameter
	}
	return 0
}

func (x *RiceDeltaEncoded128Bit) GetEntriesCount() int32 {
	if x != nil {
		return x.EntriesCount
	}
	return 0
}

func (x *RiceDeltaEncoded128Bit) GetEncodedData() []byte {
	if x != nil {
		return x.EncodedData
	}
	return nil
}

// Same as `RiceDeltaEncoded32Bit` except this encodes 256-bit numbers.
type RiceDeltaEncoded256Bit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The first 64 bits of the first entry in the encoded data (hashes). If the
	// field is empty, the first 64 bits are all zero.
	FirstValueFirstPart uint64 `protobuf:"varint,1,opt,name=first_value_first_part,json=firstValueFirstPart,proto3" json:"first_value_first_part,omitempty"`
	// The 65 through 128th bits of the first entry in the encoded data (hashes).
	// If the field is empty, the 65 through 128th bits are all zero.
	FirstValueSecondPart uint64 `protobuf:"fixed64,2,opt,name=first_value_second_part,json=firstValueSecondPart,proto3" json:"first_value_second_part,omitempty"`
	// The 129 through 192th bits of the first entry in the encoded data (hashes).
	// If the field is empty, the 129 through 192th bits are all zero.
	FirstValueThirdPart uint64 `protobuf:"fixed64,3,opt,name=first_value_third_part,json=firstValueThirdPart,proto3" json:"first_value_third_part,omitempty"`
	// The last 64 bits of the first entry in the encoded data (hashes). If the
	// field is empty, the last 64 bits are all zero.
	FirstValueFourthPart uint64 `protobuf:"fixed64,4,opt,name=first_value_fourth_part,json=firstValueFourthPart,proto3" json:"first_value_fourth_part,omitempty"`
	// The Golomb-Rice parameter. This parameter is guaranteed to be between 227
	// and 254, inclusive.
	RiceParameter int32 `protobuf:"varint,5,opt,name=rice_parameter,json=riceParameter,proto3" json:"rice_parameter,omitempty"`
	// The number of entries that are delta encoded in the encoded data. If only a
	// single integer was encoded, this will be zero and the single value will be
	// stored in `first_value`.
	EntriesCount int32 `protobuf:"varint,6,opt,name=entries_count,json=entriesCount,proto3" json:"entries_count,omitempty"`
	// The encoded deltas that are encoded using the Golomb-Rice coder.
	EncodedData   []byte `protobuf:"bytes,7,opt,name=encoded_data,json=encodedData,proto3" json:"encoded_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiceDeltaEncoded256Bit) Reset() {
	*x = RiceDeltaEncoded256Bit{}
	mi := &file_safebrowsingv5_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiceDeltaEncoded256Bit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiceDeltaEncoded256Bit) ProtoMessage() {}

func (x *RiceDeltaEncoded256Bit) ProtoReflect() protoreflect.Message {
	mi := &file_safebrowsingv5_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiceDeltaEncoded256Bit.ProtoReflect.Descriptor instead.
func (*RiceDeltaEncoded256Bit) Descriptor() ([]byte, []int) {
	return file_safebrowsingv5_proto_rawDescGZIP(), []int{8}
}

func (x *RiceDeltaEncoded256Bit) GetFirstValueFirstPart() uint64 {
	if x != nil {
		return x.FirstValueFirstPart
	}
	return 0
}

func (x *RiceDeltaEncoded256Bit) GetFirstValueSecondPart() uint64 {
	if x != nil {
		return x.FirstValueSecondPart
	}
	return 0
}

func (x *RiceDeltaEncoded256Bit) GetFirstValueThirdPart() uint64 {
	if x != nil {
		return x.FirstValueThirdPart
	}
	return 0
}

func (x *RiceDeltaEncoded256Bit) GetFirstValueFourthPart() uint64 {
	if x != nil {
		return x.FirstValueFourthPart
	}
	return 0
}

func (x *RiceDeltaEncoded256Bit) GetRiceParameter() int32 {
	if x != nil {
		return x.RiceParameter
	}
	return 0
}

func (x *RiceDeltaEncoded256Bit) GetEntriesCount() int32 {
	if x != nil {
		return x.EntriesCount
	}
	return 0
}

func (x *RiceDeltaEncoded256Bit) GetEncodedData() []byte {
	if x != nil {
		return x.EncodedData
	}
	return nil
}

// Metadata about a particular hash list.
type HashListMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If not empty, this specifies that the hash list is a kind of threat list,
	// and this enumerates the kind of threats associated with hashes or hash
	// prefixes in this hash list. May be empty if the entry does not represent a
	// threat, i.e. in the case that it represents a likely safe type.
	ThreatTypes []ThreatType `protobuf:"varint,1,rep,packed,name=threat_types,json=threatTypes,proto3,enum=safe_browsing.V5.ThreatType" json:"threat_types,omitempty"`
	// If not empty, this specifies that the hash list represents a list of likely
	// safe hashes, and this enumerates the ways they are considered likely safe.
	// This field is mutually exclusive with the threat_types field.
	LikelySafeTypes []LikelySafeType `protobuf:"varint,2,rep,packed,name=likely_safe_types,json=likelySafeTypes,proto3,enum=safe_browsing.V5.LikelySafeType" json:"likely_safe_types,omitempty"`
	// A human-readable description about this list. Written in English.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// The supported hash length for this hash list. Each hash list will support
	// exactly one length. If a different hash length is introduced for the same
	// set of threat types or safe types, it will be introduced as a separate list
	// with a distinct name and respective hash length set.
	HashLength    HashListMetadata_HashLength `protobuf:"varint,6,opt,name=hash_length,json=hashLength,proto3,enum=safe_browsing.V5.HashListMetadata_HashLength" json:"hash_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashListMetadata) Reset() {
	*x = HashListMetadata{}
	mi := &file_safebrowsingv5_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashListMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashListMetadata) ProtoMessage() {}

func (x *HashListMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_safebrowsingv5_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashListMetadata.ProtoReflect.Descriptor instead.
func (*HashListMetadata) Descriptor() ([]byte, []int) {
	return file_safebrowsingv5_proto_rawDescGZIP(), []int{9}
}

func (x *HashListMetadata) GetThreatTypes() []ThreatType {
	if x != nil {
		return x.ThreatTypes
	}
	return nil
}

func (x *HashListMetadata) GetLikelySafeTypes() []LikelySafeType {
	if x != nil {
		return x.LikelySafeTypes
	}
	return nil
}

func (x *HashListMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *HashListMetadata) GetHashLength() HashListMetadata_HashLength {
	if x != nil {
		return x.HashLength
	}
	return HashListMetadata_HASH_LENGTH_UNSPECIFIED
}

// A list of hashes identified by its name.
type HashList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the hash list. Note that the Global Cache is also just a hash
	// list and can be referred to here.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The version of the hash list. The client MUST NOT manipulate those bytes.
	Version []byte `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// When true, this is a partial diff containing additions and removals
	// based on what the client already has. When false, this is the complete
	// hash list.
	//
	// When false, the client MUST delete any locally stored version for this
	// hash list. This means that either the version possessed by the client is
	// seriously out-of-date or the client data is believed to be corrupt. The
	// `compressed_removals` field will be empty.
	//
	// When true, the client MUST apply an incremental update by applying
	// removals and then additions.
	PartialUpdate bool `protobuf:"varint,3,opt,name=partial_update,json=partialUpdate,proto3" json:"partial_update,omitempty"`
	// The Rice-delta encoded version of additions. The hash prefix lengths of
	// additions are uniform across all additions in the list.
	//
	// Types that are valid to be assigned to CompressedAdditions:
	//
	//	*HashList_AdditionsFourBytes
	//	*HashList_AdditionsEightBytes
	//	*HashList_AdditionsSixteenBytes
	//	*HashList_AdditionsThirtyTwoBytes
	CompressedAdditions isHashList_CompressedAdditions `protobuf_oneof:"compressed_additions"`
	// The Rice-delta encoded version of removal indices. Since each hash list
	// definitely has less than 2^32 entries, the indices are treated as 32-bit
	// integers and encoded.
	CompressedRemovals *RiceDeltaEncoded32Bit `protobuf:"bytes,5,opt,name=compressed_removals,json=compressedRemovals,proto3" json:"compressed_removals,omitempty"`
	// Clients should wait at least this long to get the hash list again. If
	// omitted or zero, clients SHOULD fetch immediately because it indicates that
	// the server has an additional update to be sent to the client, but could not
	// due to the client-specified constraints.
	MinimumWaitDuration *Duration `protobuf:"bytes,6,opt,name=minimum_wait_duration,json=minimumWaitDuration,proto3" json:"minimum_wait_duration,omitempty"`
	// The sorted list of all hashes, hashed again with SHA256.
	// This is the checksum for the sorted list of all hashes present in the
	// database after applying the provided update. In the case that no updates
	// were provided, the server will omit this field to indicate
	// that the client should use the existing checksum.
	Sha256Checksum []byte `protobuf:"bytes,7,opt,name=sha256_checksum,json=sha256Checksum,proto3" json:"sha256_checksum,omitempty"`
	// Metadata about the hash list. This is not populated by the `GetHashList`
	// method, but this is populated by the
	// `ListHashLists` method.
	Metadata      *HashListMetadata `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashList) Reset() {
	*x = HashList{}
	mi := &file_safebrowsingv5_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashList) ProtoMessage() {}

func (x *HashList) ProtoReflect() protoreflect.Message {
	mi := &file_safebrowsingv5_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashList.ProtoReflect.Descriptor instead.
func (*HashList) Descriptor() ([]byte, []int) {
	return file_safebrowsingv5_proto_rawDescGZIP(), []int{10}
}

func (x *HashList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HashList) GetVersion() []byte {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *HashList) GetPartialUpdate() bool {
	if x != nil {
		return x.PartialUpdate
	}
	return false
}

func (x *HashList) GetCompressedAdditions() isHashList_CompressedAdditions {
	if x != nil {
		return x.CompressedAdditions
	}
	return nil
}

func (x *HashList) GetAdditionsFourBytes() *RiceDeltaEncoded32Bit {
	if x != nil {
		if x, ok := x.CompressedAdditions.(*HashList_AdditionsFourBytes); ok {
			return x.AdditionsFourBytes
		}
	}
	return nil
}

func (x *HashList) GetAdditionsEightBytes() *RiceDeltaEncoded64Bit {
	if x != nil {
		if x, ok := x.CompressedAdditions.(*HashList_AdditionsEightBytes); ok {
			return x.AdditionsEightBytes
		}
	}
	return nil
}

func (x *HashList) GetAdditionsSixteenBytes() *RiceDeltaEncoded128Bit {
	if x != nil {
		if x, ok := x.CompressedAdditions.(*HashList_AdditionsSixteenBytes); ok {
			return x.AdditionsSixteenBytes
		}
	}
	return nil
}

func (x *HashList) GetAdditionsThirtyTwoBytes() *RiceDeltaEncoded256Bit {
	if x != nil {
		if x, ok := x.CompressedAdditions.(*HashList_AdditionsThirtyTwoBytes); ok {
			return x.AdditionsThirtyTwoBytes
		}
	}
	return nil
}

func (x *HashList) GetCompressedRemovals() *RiceDeltaEncoded32Bit {
	if x != nil {
		return x.CompressedRemovals
	}
	return nil
}

func (x *HashList) GetMinimumWaitDuration() *Duration {
	if x != nil {
		return x.MinimumWaitDuration
	}
	return nil
}

func (x *HashList) GetSha256Checksum() []byte {
	if x != nil {
		return x.Sha256Checksum
	}
	return nil
}

func (x *HashList) GetMetadata() *HashListMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isHashList_CompressedAdditions interface {
	isHashList_CompressedAdditions()
}

type HashList_AdditionsFourBytes struct {
	// The 4-byte additions.
	AdditionsFourBytes *RiceDeltaEncoded32Bit `protobuf:"bytes,4,opt,name=additions_four_bytes,json=additionsFourBytes,proto3,oneof"`
}

type HashList_AdditionsEightBytes struct {
	// The 8-byte additions.
	AdditionsEightBytes *RiceDeltaEncoded64Bit `protobuf:"bytes,9,opt,name=additions_eight_bytes,json=additionsEightBytes,proto3,oneof"`
}

type HashList_AdditionsSixteenBytes struct {
	// The 16-byte additions.
	AdditionsSixteenBytes *RiceDeltaEncoded128Bit `protobuf:"bytes,10,opt,name=additions_sixteen_bytes,json=additionsSixteenBytes,proto3,oneof"`
}

type HashList_AdditionsThirtyTwoBytes struct {
	// The 32-byte additions.
	AdditionsThirtyTwoBytes *RiceDeltaEncoded256Bit `protobuf:"bytes,11,opt,name=additions_thirty_two_bytes,json=additionsThirtyTwoBytes,proto3,oneof"`
}

func (*HashList_AdditionsFourBytes) isHashList_CompressedAdditions() {}

func (*HashList_AdditionsEightBytes) isHashList_CompressedAdditions() {}

func (*HashList_AdditionsSixteenBytes) isHashList_CompressedAdditions() {}

func (*HashList_AdditionsThirtyTwoBytes) isHashList_CompressedAdditions() {}

// The request to get multiple hash lists at the same time.
type BatchGetHashListsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The names of the particular hash lists. The list MAY be a threat list, or
	// it may be the Global Cache. The names MUST NOT contain duplicates; if they
	// did, the client will get an error.
	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	// The versions of the hash list that the client already has. If this is the
	// first time the client is fetching the hash lists, the field should be
	// left empty. Otherwise, the client should supply the versions previously
	// received from the server. The client MUST NOT manipulate those bytes.
	//
	// The client need not send the versions in the same order as the
	// corresponding list names. The client may send fewer or more versions in a
	// request than there are names. However the client MUST NOT send multiple
	// versions that correspond to the same name; if it did, the client will get
	// an error.
	//
	// Historical note: in V4 of the API, this was called
	// `states`; it is now renamed to `version` for clarity.
	Version [][]byte `protobuf:"bytes,2,rep,name=version,proto3" json:"version,omitempty"`
	// The size constraints on each list. If omitted, there are no
	// constraints. Note that the sizes here are per-list, not aggregated across
	// all lists.
	SizeConstraints *SizeConstraints `protobuf:"bytes,4,opt,name=size_constraints,json=sizeConstraints,proto3" json:"size_constraints,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchGetHashListsRequest) Reset() {
	*x = BatchGetHashListsRequest{}
	mi := &file_safebrowsingv5_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetHashListsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetHashListsRequest) ProtoMessage() {}

func (x *BatchGetHashListsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_safebrowsingv5_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetHashListsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetHashListsRequest) Descriptor() ([]byte, []int) {
	return file_safebrowsingv5_proto_rawDescGZIP(), []int{11}
}

func (x *BatchGetHashListsRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *BatchGetHashListsRequest) GetVersion() [][]byte {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *BatchGetHashListsRequest) GetSizeConstraints() *SizeConstraints {
	if x != nil {
		return x.SizeConstraints
	}
	return nil
}

// The response containing multiple hash lists.
type BatchGetHashListsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The hash lists in the same order given in the request.
	HashLists     []*HashList `protobuf:"bytes,1,rep,name=hash_lists,json=hashLists,proto3" json:"hash_lists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetHashListsResponse) Reset() {
	*x = BatchGetHashListsResponse{}
	mi := &file_safebrowsingv5_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetHashListsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetHashListsResponse) ProtoMessage() {}

func (x *BatchGetHashListsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_safebrowsingv5_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetHashListsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetHashListsResponse) Descriptor() ([]byte, []int) {
	return file_safebrowsingv5_proto_rawDescGZIP(), []int{12}
}

func (x *BatchGetHashListsResponse) GetHashLists() []*HashList {
	if x != nil {
		return x.HashLists
	}
	return nil
}

// Details about a matching full hash.
//
// An important note about forward compatibility: new threat types and threat
// attributes may be added by the server at any time; those additions are
// considered minor version changes. It is Google's policy not to expose minor
// version numbers in APIs (see
// https://cloud.google.com/apis/design/versioning), so clients MUST be
// prepared to receive FullHashDetail messages containing ThreatType enum
// values or ThreatAttribute enum values that are considered invalid by the
// client. Therefore, it is the client's responsibility to check for the
// validity of all ThreatType and ThreatAttribute enum values; if any value is
// considered invalid, the client MUST disregard the entire FullHashDetail
// message.
type FullHash_FullHashDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of threat. This field will never be empty.
	ThreatType ThreatType `protobuf:"varint,1,opt,name=threat_type,json=threatType,proto3,enum=safe_browsing.V5.ThreatType" json:"threat_type,omitempty"`
	// Additional attributes about those full hashes. This may be empty.
	Attributes    []ThreatAttribute `protobuf:"varint,2,rep,packed,name=attributes,proto3,enum=safe_browsing.V5.ThreatAttribute" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullHash_FullHashDetail) Reset() {
	*x = FullHash_FullHashDetail{}
	mi := &file_safebrowsingv5_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullHash_FullHashDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullHash_FullHashDetail) ProtoMessage() {}

func (x *FullHash_FullHashDetail) ProtoReflect() protoreflect.Message {
	mi := &file_safebrowsingv5_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullHash_FullHashDetail.ProtoReflect.Descriptor instead.
func (*FullHash_FullHashDetail) Descriptor() ([]byte, []int) {
	return file_safebrowsingv5_proto_rawDescGZIP(), []int{2, 0}
}

func (x *FullHash_FullHashDetail) GetThreatType() ThreatType {
	if x != nil {
		return x.ThreatType
	}
	return ThreatType_THREAT_TYPE_UNSPECIFIED
}

func (x *FullHash_FullHashDetail) GetAttributes() []ThreatAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_safebrowsingv5_proto protoreflect.FileDescriptor

const file_safebrowsingv5_proto_rawDesc = "" +
	"\n" +
	"\x14safebrowsingv5.proto\x12\x10safe_browsing.V5\"F\n" +
	"\x13SearchHashesRequest\x12#\n" +
	"\rhash_prefixes\x18\x01 \x03(\fR\fhashPrefixesJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04\"\x96\x01\n" +
	"\x14SearchHashesResponse\x12;\n" +
	"\vfull_hashes\x18\x01 \x03(\v2\x1a.safe_browsing.V5.FullHashR\n" +
	"fullHashes\x12A\n" +
	"\x0ecache_duration\x18\x02 \x01(\v2\x1a.safe_browsing.V5.DurationR\rcacheDuration\"\x93\x02\n" +
	"\bFullHash\x12\x1b\n" +
	"\tfull_hash\x18\x01 \x01(\fR\bfullHash\x12U\n" +
	"\x11full_hash_details\x18\x02 \x03(\v2).safe_browsing.V5.FullHash.FullHashDetailR\x0ffullHashDetails\x1a\x92\x01\n" +
	"\x0eFullHashDetail\x12=\n" +
	"\vthreat_type\x18\x01 \x01(\x0e2\x1c.safe_browsing.V5.ThreatTypeR\n" +
	"threatType\x12A\n" +
	"\n" +
	"attributes\x18\x02 \x03(\x0e2!.safe_browsing.V5.ThreatAttributeR\n" +
	"attributes\":\n" +
	"\bDuration\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanos\"q\n" +
	"\x0fSizeConstraints\x12,\n" +
	"\x12max_update_entries\x18\x01 \x01(\x05R\x10maxUpdateEntries\x120\n" +
	"\x14max_database_entries\x18\x02 \x01(\x05R\x12maxDatabaseEntries\"\xa7\x01\n" +
	"\x15RiceDeltaEncoded32Bit\x12\x1f\n" +
	"\vfirst_value\x18\x01 \x01(\rR\n" +
	"firstValue\x12%\n" +
	"\x0erice_parameter\x18\x02 \x01(\x05R\rriceParameter\x12#\n" +
	"\rentries_count\x18\x03 \x01(\x05R\fentriesCount\x12!\n" +
	"\fencoded_data\x18\x04 \x01(\fR\vencodedData\"\xa7\x01\n" +
	"\x15RiceDeltaEncoded64Bit\x12\x1f\n" +
	"\vfirst_value\x18\x01 \x01(\x04R\n" +
	"firstValue\x12%\n" +
	"\x0erice_parameter\x18\x02 \x01(\x05R\rriceParameter\x12#\n" +
	"\rentries_count\x18\x03 \x01(\x05R\fentriesCount\x12!\n" +
	"\fencoded_data\x18\x04 \x01(\fR\vencodedData\"\xd3\x01\n" +
	"\x16RiceDeltaEncoded128Bit\x12$\n" +
	"\x0efirst_value_hi\x18\x01 \x01(\x04R\ffirstValueHi\x12$\n" +
	"\x0efirst_value_lo\x18\x02 \x01(\x06R\ffirstValueLo\x12%\n" +
	"\x0erice_parameter\x18\x03 \x01(\x05R\rriceParameter\x12#\n" +
	"\rentries_count\x18\x04 \x01(\x05R\fentriesCount\x12!\n" +
	"\fencoded_data\x18\x05 \x01(\fR\vencodedData\"\xdf\x02\n" +
	"\x16RiceDeltaEncoded256Bit\x123\n" +
	"\x16first_value_first_part\x18\x01 \x01(\x04R\x13firstValueFirstPart\x125\n" +
	"\x17first_value_second_part\x18\x02 \x01(\x06R\x14firstValueSecondPart\x123\n" +
	"\x16first_value_third_part\x18\x03 \x01(\x06R\x13firstValueThirdPart\x125\n" +
	"\x17first_value_fourth_part\x18\x04 \x01(\x06R\x14firstValueFourthPart\x12%\n" +
	"\x0erice_parameter\x18\x05 \x01(\x05R\rriceParameter\x12#\n" +
	"\rentries_count\x18\x06 \x01(\x05R\fentriesCount\x12!\n" +
	"\fencoded_data\x18\a \x01(\fR\vencodedData\"\x94\x03\n" +
	"\x10HashListMetadata\x12?\n" +
	"\fthreat_types\x18\x01 \x03(\x0e2\x1c.safe_browsing.V5.ThreatTypeR\vthreatTypes\x12L\n" +
	"\x11likely_safe_types\x18\x02 \x03(\x0e2 .safe_browsing.V5.LikelySafeTypeR\x0flikelySafeTypes\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12N\n" +
	"\vhash_length\x18\x06 \x01(\x0e2-.safe_browsing.V5.HashListMetadata.HashLengthR\n" +
	"hashLength\"s\n" +
	"\n" +
	"HashLength\x12\x1b\n" +
	"\x17HASH_LENGTH_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"FOUR_BYTES\x10\x02\x12\x0f\n" +
	"\vEIGHT_BYTES\x10\x03\x12\x11\n" +
	"\rSIXTEEN_BYTES\x10\x04\x12\x14\n" +
	"\x10THIRTY_TWO_BYTES\x10\x05J\x04\b\x03\x10\x04J\x04\b\x05\x10\x06\"\x93\x06\n" +
	"\bHashList\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\fR\aversion\x12%\n" +
	"\x0epartial_update\x18\x03 \x01(\bR\rpartialUpdate\x12[\n" +
	"\x14additions_four_bytes\x18\x04 \x01(\v2'.safe_browsing.V5.RiceDeltaEncoded32BitH\x00R\x12additionsFourBytes\x12]\n" +
	"\x15additions_eight_bytes\x18\t \x01(\v2'.safe_browsing.V5.RiceDeltaEncoded64BitH\x00R\x13additionsEightBytes\x12b\n" +
	"\x17additions_sixteen_bytes\x18\n" +
	" \x01(\v2(.safe_browsing.V5.RiceDeltaEncoded128BitH\x00R\x15additionsSixteenBytes\x12g\n" +
	"\x1aadditions_thirty_two_bytes\x18\v \x01(\v2(.safe_browsing.V5.RiceDeltaEncoded256BitH\x00R\x17additionsThirtyTwoBytes\x12X\n" +
	"\x13compressed_removals\x18\x05 \x01(\v2'.safe_browsing.V5.RiceDeltaEncoded32BitR\x12compressedRemovals\x12N\n" +
	"\x15minimum_wait_duration\x18\x06 \x01(\v2\x1a.safe_browsing.V5.DurationR\x13minimumWaitDuration\x12'\n" +
	"\x0fsha256_checksum\x18\a \x01(\fR\x0esha256Checksum\x12>\n" +
	"\bmetadata\x18\b \x01(\v2\".safe_browsing.V5.HashListMetadataR\bmetadataB\x16\n" +
	"\x14compressed_additions\"\x9e\x01\n" +
	"\x18BatchGetHashListsRequest\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\x12\x18\n" +
	"\aversion\x18\x02 \x03(\fR\aversion\x12L\n" +
	"\x10size_constraints\x18\x04 \x01(\v2!.safe_browsing.V5.SizeConstraintsR\x0fsizeConstraintsJ\x04\b\x03\x10\x04\"V\n" +
	"\x19BatchGetHashListsResponse\x129\n" +
	"\n" +
	"hash_lists\x18\x01 \x03(\v2\x1a.safe_browsing.V5.HashListR\thashLists*\xc9\x02\n" +
	"\n" +
	"ThreatType\x12\x1b\n" +
	"\x17THREAT_TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aMALWARE\x10\x01\x12\x16\n" +
	"\x12SOCIAL_ENGINEERING\x10\x02\x12\x15\n" +
	"\x11UNWANTED_SOFTWARE\x10\x03\x12#\n" +
	"\x1fPOTENTIALLY_HARMFUL_APPLICATION\x10\x04\x12\x14\n" +
	"\x10MALICIOUS_BINARY\x10\a\x12\x16\n" +
	"\x12SUBRESOURCE_FILTER\x10\r\x12\x11\n" +
	"\rTRICK_TO_BILL\x10\x0f\x12 \n" +
	"\x1cABUSIVE_EXPERIENCE_VIOLATION\x10\x14\x12\x18\n" +
	"\x14BETTER_ADS_VIOLATION\x10\x15\x12\x16\n" +
	"\x12NOTIFICATION_ABUSE\x10\x18\"\x04\b\x05\x10\x05\"\x04\b\x06\x10\x06\"\x04\b\b\x10\f\"\x04\b\x0e\x10\x0e\"\x04\b\x10\x10\x13\"\x04\b\x16\x10\x16\"\x04\b\x17\x10\x17*O\n" +
	"\x0fThreatAttribute\x12 \n" +
	"\x1cTHREAT_ATTRIBUTE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06CANARY\x10\x01\x12\x0e\n" +
	"\n" +
	"FRAME_ONLY\x10\x02*_\n" +
	"\x0eLikelySafeType\x12 \n" +
	"\x1cLIKELY_SAFE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10GENERAL_BROWSING\x10\x01\x12\a\n" +
	"\x03CSD\x10\x02\x12\f\n" +
	"\bDOWNLOAD\x10\x03BAH\x03Z=github.com/stop-error/safebrowsingv5/internal/safebrowsing_pbb\x06proto3"

var (
	file_safebrowsingv5_proto_rawDescOnce sync.Once
	file_safebrowsingv5_proto_rawDescData []byte
)

func file_safebrowsingv5_proto_rawDescGZIP() []byte {
	file_safebrowsingv5_proto_rawDescOnce.Do(func() {
		file_safebrowsingv5_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_safebrowsingv5_proto_rawDesc), len(file_safebrowsingv5_proto_rawDesc)))
	})
	return file_safebrowsingv5_proto_rawDescData
}

var file_safebrowsingv5_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_safebrowsingv5_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_safebrowsingv5_proto_goTypes = []any{
	(ThreatType)(0),                   // 0: safe_browsing.V5.ThreatType
	(ThreatAttribute)(0),              // 1: safe_browsing.V5.ThreatAttribute
	(LikelySafeType)(0),               // 2: safe_browsing.V5.LikelySafeType
	(HashListMetadata_HashLength)(0),  // 3: safe_browsing.V5.HashListMetadata.HashLength
	(*SearchHashesRequest)(nil),       // 4: safe_browsing.V5.SearchHashesRequest
	(*SearchHashesResponse)(nil),      // 5: safe_browsing.V5.SearchHashesResponse
	(*FullHash)(nil),                  // 6: safe_browsing.V5.FullHash
	(*Duration)(nil),                  // 7: safe_browsing.V5.Duration
	(*SizeConstraints)(nil),           // 8: safe_browsing.V5.SizeConstraints
	(*RiceDeltaEncoded32Bit)(nil),     // 9: safe_browsing.V5.RiceDeltaEncoded32Bit
	(*RiceDeltaEncoded64Bit)(nil),     // 10: safe_browsing.V5.RiceDeltaEncoded64Bit
	(*RiceDeltaEncoded128Bit)(nil),    // 11: safe_browsing.V5.RiceDeltaEncoded128Bit
	(*RiceDeltaEncoded256Bit)(nil),    // 12: safe_browsing.V5.RiceDeltaEncoded256Bit
	(*HashListMetadata)(nil),          // 13: safe_browsing.V5.HashListMetadata
	(*HashList)(nil),                  // 14: safe_browsing.V5.HashList
	(*BatchGetHashListsRequest)(nil),  // 15: safe_browsing.V5.BatchGetHashListsRequest
	(*BatchGetHashListsResponse)(nil), // 16: safe_browsing.V5.BatchGetHashListsResponse
	(*FullHash_FullHashDetail)(nil),   // 17: safe_browsing.V5.FullHash.FullHashDetail
}
var file_safebrowsingv5_proto_depIdxs = []int32{
	6,  // 0: safe_browsing.V5.SearchHashesResponse.full_hashes:type_name -> safe_browsing.V5.FullHash
	7,  // 1: safe_browsing.V5.SearchHashesResponse.cache_duration:type_name -> safe_browsing.V5.Duration
	17, // 2: safe_browsing.V5.FullHash.full_hash_details:type_name -> safe_browsing.V5.FullHash.FullHashDetail
	0,  // 3: safe_browsing.V5.HashListMetadata.threat_types:type_name -> safe_browsing.V5.ThreatType
	2,  // 4: safe_browsing.V5.HashListMetadata.likely_safe_types:type_name -> safe_browsing.V5.LikelySafeType
	3,  // 5: safe_browsing.V5.HashListMetadata.hash_length:type_name -> safe_browsing.V5.HashListMetadata.HashLength
	9,  // 6: safe_browsing.V5.HashList.additions_four_bytes:type_name -> safe_browsing.V5.RiceDeltaEncoded32Bit
	10, // 7: safe_browsing.V5.HashList.additions_eight_bytes:type_name -> safe_browsing.V5.RiceDeltaEncoded64Bit
	11, // 8: safe_browsing.V5.HashList.additions_sixteen_bytes:type_name -> safe_browsing.V5.RiceDeltaEncoded128Bit
	12, // 9: safe_browsing.V5.HashList.additions_thirty_two_bytes:type_name -> safe_browsing.V5.RiceDeltaEncoded256Bit
	9,  // 10: safe_browsing.V5.HashList.compressed_removals:type_name -> safe_browsing.V5.RiceDeltaEncoded32Bit
	7,  // 11: safe_browsing.V5.HashList.minimum_wait_duration:type_name -> safe_browsing.V5.Duration
	13, // 12: safe_browsing.V5.HashList.metadata:type_name -> safe_browsing.V5.HashListMetadata
	8,  // 13: safe_browsing.V5.BatchGetHashListsRequest.size_constraints:type_name -> safe_browsing.V5.SizeConstraints
	14, // 14: safe_browsing.V5.BatchGetHashListsResponse.hash_lists:type_name -> safe_browsing.V5.HashList
	0,  // 15: safe_browsing.V5.FullHash.FullHashDetail.threat_type:type_name -> safe_browsing.V5.ThreatType
	1,  // 16: safe_browsing.V5.FullHash.FullHashDetail.attributes:type_name -> safe_browsing.V5.ThreatAttribute
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_safebrowsingv5_proto_init() }
func file_safebrowsingv5_proto_init() {
	if File_safebrowsingv5_proto != nil {
		return
	}
	file_safebrowsingv5_proto_msgTypes[10].OneofWrappers = []any{
		(*HashList_AdditionsFourBytes)(nil),
		(*HashList_AdditionsEightBytes)(nil),
		(*HashList_AdditionsSixteenBytes)(nil),
		(*HashList_AdditionsThirtyTwoBytes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_safebrowsingv5_proto_rawDesc), len(file_safebrowsingv5_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_safebrowsingv5_proto_goTypes,
		DependencyIndexes: file_safebrowsingv5_proto_depIdxs,
		EnumInfos:         file_safebrowsingv5_proto_enumTypes,
		MessageInfos:      file_safebrowsingv5_proto_msgTypes,
	}.Build()
	File_safebrowsingv5_proto = out.File
	file_safebrowsingv5_proto_goTypes = nil
	file_safebrowsingv5_proto_depIdxs = nil
}
